### ISSUE TITLE
异常操作

### ISSUE THREAD

**Issue by CerebellarAxe** [tuChanged/SimpleIcveMoocHelper#17]
无任务可分配 
{code: -2, msg: "异常操作！"}
code: -2
msg: "异常操作！"
__proto__:
constructor: ƒ Object()
hasOwnProperty: ƒ hasOwnProperty()
isPrototypeOf: ƒ isPrototypeOf()
propertyIsEnumerable: ƒ propertyIsEnumerable()
toLocaleString: ƒ toLocaleString()
toString: ƒ toString()
valueOf: ƒ valueOf()
__defineGetter__: ƒ __defineGetter__()
__defineSetter__: ƒ __defineSetter__()
__lookupGetter__: ƒ __lookupGetter__()
__lookupSetter__: ƒ __lookupSetter__()
get __proto__: ƒ __proto__()
set __proto__: ƒ __proto__()

**Comment by tuchg** [comment]
无所谓可以，忽略
