### ISSUE TITLE
这样做真的的好么？

### ISSUE THREAD

**Issue by lichangyuan1993** [tuChanged/SimpleIcveMoocHelper#22]
真希望那些看到这个项目的学生不要用来无脑刷课时。

**Comment by tuchg** [comment]
可能不会有多少同学会看到这个

**Comment by lichangyuan1993** [comment]
没试过你的代码，但是感觉你的技术不错。



lichangyuan1126@foxmail.com
 
发件人： tuchg
发送时间： 2020-09-21 16:45
收件人： tuchg/SimpleICVEMOOCHelper
抄送： lichangyuan; Author
主题： Re: [tuchg/SimpleICVEMOOCHelper] 这样做真的的好么？ (#22)
可能不会有多少同学会看到这个
