### ISSUE TITLE
不能实现自动下一个视频或者文档或者ppt吗？

### ISSUE THREAD

**Issue by YUZAIHAILIKU** [tuChanged/SimpleIcveMoocHelper#3]
我这边看完一个视频就会自动评论然后不动了 没有人工干预一直不会动

**Comment by tuchg** [comment]
有自动的,没自动还叫啥脚本呢,会有一定随机间隔时间,耐心等候一下就OK

**Comment by YUZAIHAILIKU** [comment]
非常感谢您的回复 那我再去试试 我的小节里面有视频 有的小节有ppt或者文档 好像不会跳 我等了十分钟 而且会出现错误代码 好像是把一个非函数当函数去调了。

**Comment by YUZAIHAILIKU** [comment]
非常感谢您的回复 那我再去试试 我的小节里面有视频 有的小节有ppt或者文档 好像不会跳 我等了十分钟 而且会出现错误代码 好像是把一个非函数当函数去调了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "W-ChihC"<notifications@github.com&gt;; 
发送时间: 2020年2月16日(星期天) 下午4:33
收件人: "W-ChihC/SimpleIcveMoocHelper"<SimpleIcveMoocHelper@noreply.github.com&gt;; 
抄送: "鱼在海里哭"<347848081@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [W-ChihC/SimpleIcveMoocHelper] 不能实现自动下一个视频或者文档或者ppt吗？ (#3)




有自动的,没自动还叫啥脚本呢,会有一定随机间隔时间,耐心等候一下就OK

**Comment by tuchg** [comment]
> 非常感谢您的回复 那我再去试试 我的小节里面有视频 有的小节有ppt或者文档 好像不会跳 我等了十分钟 而且会出现错误代码 好像是把一个非函数当函数去调了。

ok,你可以把错误信息贴出来,这个非函数应该没问题,有些错误是网站自己就有的

**Comment by YUZAIHAILIKU** [comment]
具体setDelayExec(func)这个函数里的await func()
这句扔的异常，报func is not a function。
我当时打log，一直到评论这个活动前，这个func都是正常的函数，评论结束后，再log出来，就是undefined

**Comment by tuchg** [comment]
这个问题可以忽略掉,可能是检索下一级的时候递归出了问题,你可以在check函数里打个断点看看

或者跳过你当前的下一节课程看看能不能正常检索,不排除递归过程的bug,我的样本还是比较少的,有些复杂的情况可能没有考虑到

**Comment by YUZAIHAILIKU** [comment]
| success | @ | directory-d5ee2a737c.js:1
-- | -- | -- | --

**Comment by YUZAIHAILIKU** [comment]
userscript.html?id=e…2f7-1183411c77a7:58 Uncaught (in promise) TypeError: func is not a function     at Window.eval (userscript.html?id=e…2f7-1183411c77a7:58)     at <anonymous&gt;:3:75     at c.<computed&gt; (eval at exec_fn (directory.html?cours…f6rb79lhsfcsc2zdw:1), <anonymous&gt;:55:204)




7
directory-d5ee2a737c.js:1 366.734

102
directory-d5ee2a737c.js:1 Uncaught TypeError: l.getPosition is not a function     at Object.success (directory-d5ee2a737c.js:1)     at h (framework-d6b27c488e.js:1)     at Object.fireWith [as resolveWith] (framework-d6b27c488e.js:1)     at n (framework-d6b27c488e.js:3)     at XMLHttpRequest.n (framework-d6b27c488e.js:3)
success@directory-d5ee2a737c.js:1










------------------&nbsp;原始邮件&nbsp;------------------
发件人: "W-ChihC"<notifications@github.com&gt;; 
发送时间: 2020年2月17日(星期一) 中午11:54
收件人: "W-ChihC/SimpleIcveMoocHelper"<SimpleIcveMoocHelper@noreply.github.com&gt;; 
抄送: "鱼在海里哭"<347848081@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [W-ChihC/SimpleIcveMoocHelper] 不能实现自动下一个视频或者文档或者ppt吗？ (#3)




这个问题可以忽略掉,可能是检索下一级的时候递归出了问题,你可以在check函数里打个断点看看
 
或者跳过你当前的下一节课程看看能不能正常检索,不排除递归过程的bug,我的样本还是比较少的,有些复杂的情况可能没有考虑到

**Comment by YUZAIHAILIKU** [comment]
可以加个微信交流一下吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "W-ChihC"<notifications@github.com&gt;; 
发送时间: 2020年2月17日(星期一) 中午11:54
收件人: "W-ChihC/SimpleIcveMoocHelper"<SimpleIcveMoocHelper@noreply.github.com&gt;; 
抄送: "鱼在海里哭"<347848081@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [W-ChihC/SimpleIcveMoocHelper] 不能实现自动下一个视频或者文档或者ppt吗？ (#3)




这个问题可以忽略掉,可能是检索下一级的时候递归出了问题,你可以在check函数里打个断点看看
 
或者跳过你当前的下一节课程看看能不能正常检索,不排除递归过程的bug,我的样本还是比较少的,有些复杂的情况可能没有考虑到

**Comment by tuchg** [comment]
刚自己测试了下,运行正常,我加你QQ吧

**Comment by tuchg** [comment]
已提供兼容内嵌文件夹课件

**Comment by AI-fairytale** [comment]
刚注册的， 来看看

**Comment by 123zxc321232** [comment]
我的也是  都不能自己运行，求大哥指导指导。

**Comment by 123zxc321232** [comment]
2259310795，大神看到了麻烦加下qq，谢谢了。我搞了几次都不行，蒙了

**Comment by YUZAIHAILIKU** [comment]
我不是开发者，请联系开发者。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月12日(星期三) 上午7:59
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [tuchg/SimpleICVEMOOCHelper] 不能实现自动下一个视频或者文档或者ppt吗？ (#3)





 
2259310795，大神看到了麻烦加下qq，谢谢了。我搞了几次都不行，蒙了

**Comment by kwptsuno** [comment]
没法用，青版的我这边看完一个视频下一个就不动了如果没有人工干预一直不会动，其他的几个没法用啊。afanofs.holmesisge@qq.com

**Comment by a568983760** [comment]
求大哥指导职教云的怎么使用  大哥加我微信18760065282

**Comment by 51651441** [comment]
您好这个具体怎么使用
可以加一下我qq3476187126

**Comment by 51651441** [comment]
求大哥加qq3476187126

**Comment by huanhuantiantian** [comment]
我开也不会自己跳欸
