### ISSUE TITLE
绿版刷课件失效 具体原因不清楚 主要看到了以下报错

### ISSUE THREAD

**Issue by Aditems** [tuChanged/SimpleIcveMoocHelper#7]
Unchecked runtime.lastError: The message port closed before a response was received.
process.html?courseOpenId=skr2av2rl5tazb7isn5wg&openClassId=sqw4af6rzbppusufmgadg:1 

点开后提示
A cookie associated with a cross-site resource at http://hephelp.udesk.cn/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
2
Unchecked runtime.lastError: The message port closed before a response was received.
A cookie associated with a cross-site resource at http://basevistor.udesk.cn/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.

**Comment by tuchg** [comment]
这个是和脚本无关的报错,出现报错,点弹窗就行
