### ISSUE TITLE
Uncaught ReferenceError: isOpenComment is not defined

### ISSUE THREAD

**Issue by hanajoruno** [tuChanged/SimpleIcveMoocHelper#8]
blue 1.08 在224行报错Uncaught ReferenceError: isOpenComment is not defined 刷课件时不会自动下一个 isOpenComment 改为true后不进行评论
1.07版刷的时候无上述问题 但会跳过每小节第一个视频

**Comment by tuchg** [comment]
不好意思,失误失误,改过来了
