### ISSUE TITLE
ppt模式到一半就变成文档模式

### ISSUE THREAD

**Issue by SiH-zh** [tuChanged/SimpleIcveMoocHelper#9]
进入一个未学习的ppt一开始是自动点的，然后不知道怎么了就开始按照文档的模式每个10秒才点一下
![QQ截图20200406155647](https://user-images.githubusercontent.com/61227595/78535969-a5d8f580-781f-11ea-8e42-e8ea9c4bcff7.png)

**Comment by tuchg** [comment]
正常现象,后面的自动点是为了防止课件漏刷,固定10秒是因为网站代码是这么写的
